### ISSUE TITLE
missing setup.py

### ISSUE THREAD

**Issue by Sigfried** [HOT-Ecosystem/ValueSet-Converters#3]
Do I need my own setup.py? Or is that a standard thing that ought to be in my environment or something?

```
➜ make build
rm -rf ./dist;
rm -rf ./build;
rm -rf ./*.egg-info
python3 setup.py sdist bdist_wheel
/Users/sigfried/.pyenv/versions/3.9.6/bin/python3: can't open file '/Users/sigfried/bin/fetchvs/ValueSet-Converters/setup.py': [Errno 2] No such file or directory
make: *** [build] Error 2
```

**Comment by joeflack4** [comment]
Ahhh

This `makefile` is part of the boilerplate template project I created this repository from.

You can ignore it for now.

The `setup.py` and these corresponding commands that use it are for deploying this as a PyPi package so that people can install it on pip. I have no plans to do that right now, unless people think it would be useful.

It is easy to do that though. I can teach you how if you ever want.
